package org.omnione.did.wallet.exception;

public enum IWErrorCode implements IWErrorEnumInterface {
	ERR_CODE_NONE(0, "No Error occurs"), 
	ERR_CODE_CRYPTOHELPER_ENCRYPT(100,  "Failed to encrypt"), 
	ERR_CODE_CRYPTOHELPER_DECRYPT(101, 	"Failed to decrypt"), 
	ERR_CODE_CRYPTOHELPER_SIGN(102, 	"Failed to sign"),
	ERR_CODE_CRYPTOHELPER_VERIFY(103, 	"Failed to verify"), 
	ERR_CODE_CRYPTOHELPER_GENSRANDOM_FAIL(104, "Failed to generate random byte"),

	ERR_CODE_STRING_CONVERT_TO_BYTE(200, "Failed to convert string to byte"),

	
	
	ERR_CODE_KEYMANAGER_BASE(1000, ""), 
	ERR_CODE_KEYMANAGER_LOCKED(ERR_CODE_KEYMANAGER_BASE, 				0, "KeyManager is locked"),
	
	ERR_CODE_KEYMANAGER_FILE_LOAD_FAIL(ERR_CODE_KEYMANAGER_BASE, 		2, "Failed to load the WalletFile"),
	ERR_CODE_KEYMANAGER_FILE_WRITE_FAIL(ERR_CODE_KEYMANAGER_BASE, 		3, "Failed to write the WalletFile"),


	
	ERR_CODE_KEYMANAGER_KEY_BASE(1010, ""),
	ERR_CODE_KEYMANAGER_KEYID_NOT_EXIST(ERR_CODE_KEYMANAGER_KEY_BASE, 		0, "The keyId does not exist"),
	ERR_CODE_KEYMANAGER_KEYID_ALREADY_EXIST(ERR_CODE_KEYMANAGER_KEY_BASE, 	1, "The KeyId is already existed"),
	ERR_CODE_KEYMANAGER_KEYID_EMPTY_NAME(ERR_CODE_KEYMANAGER_KEY_BASE, 		2, "The Name for KeyId is empty"),
	ERR_CODE_KEYMANAGER_INVALID_ALGORITHM_TYPE(ERR_CODE_KEYMANAGER_KEY_BASE, 	3,	"Algorithm type is invalid"),
	ERR_CODE_KEYMANAGER_INVALID_KEYID_NAME(ERR_CODE_KEYMANAGER_KEY_BASE, 	4,	"The Name for KeyId must only be alphaNumeric"),
	ERR_CODE_KEYMANAGER_IWKEY_IS_NULL (ERR_CODE_KEYMANAGER_KEY_BASE, 		5,	"IWKey is null"),
	ERR_CODE_KEYMANAGER_INVALID_PRIVATE_KEY (ERR_CODE_KEYMANAGER_KEY_BASE, 	6,	"Invalid PrivateKey"),
	ERR_CODE_KEYMANAGER_INVALID_PUBLIC_KEY (ERR_CODE_KEYMANAGER_KEY_BASE, 	7,	"Invalid PublicKey"),

	
	
	ERR_CODE_KEYMANAGER_PASSWORD_BASE(1020, ""),
	ERR_CODE_KEYMANAGER_PASSWORD_NOT_SET(ERR_CODE_KEYMANAGER_PASSWORD_BASE, 						0,	"The password does not set"),
	ERR_CODE_KEYMANAGER_PASSWORD_NOT_MATCH_WITH_THE_SET_ONE(ERR_CODE_KEYMANAGER_PASSWORD_BASE, 		1,	"The password does not match with the set one"),
	ERR_CODE_KEYMANAGER_INVALID_PASSWORD(ERR_CODE_KEYMANAGER_PASSWORD_BASE, 						2,	"The password is(are) invalid for use"),
	ERR_CODE_KEYMANAGER_PASSWORD_SAME_AS_OLD(ERR_CODE_KEYMANAGER_PASSWORD_BASE, 					3,	"New password is the same as the old one"),
	
	
	ERR_CODE_KEYMANAGER_CRYPTO_BASE(1030, ""),
	ERR_CODE_KEYMANAGER_AES_ENCRYPT_FAIL(ERR_CODE_KEYMANAGER_CRYPTO_BASE, 		0, "AES Encryption is failed"),
	ERR_CODE_KEYMANAGER_AES_DECRYPT_FAIL(ERR_CODE_KEYMANAGER_CRYPTO_BASE, 		1, "AES Decryption is failed"),
	ERR_CODE_KEYMANAGER_RSA_ENCRYPT_FAIL(ERR_CODE_KEYMANAGER_CRYPTO_BASE, 		0, "RSA Encryption is failed"),
	ERR_CODE_KEYMANAGER_RSA_DECRYPT_FAIL(ERR_CODE_KEYMANAGER_CRYPTO_BASE, 		1, "RSA Decryption is failed"),


	ERR_CODE_KEYMANAGER_SIGN_BASE(1040, ""),
	ERR_CODE_KEYMANAGER_SIGN_FAIL(ERR_CODE_KEYMANAGER_SIGN_BASE, 				0, "Failed to sign data"),
	ERR_CODE_KEYMANAGER_VERIFY_SIGN_FAIL(ERR_CODE_KEYMANAGER_SIGN_BASE, 		1, "Verify signature is failed"),
	ERR_CODE_KEYMANAGER_INVALID_SIGN_VALUE(ERR_CODE_KEYMANAGER_SIGN_BASE, 		2, "Sign value is invalid"),
	ERR_CODE_KEYMANAGER_INVALID_PROFILE(ERR_CODE_KEYMANAGER_SIGN_BASE, 		3, "Profile is invalid"),
	ERR_CODE_KEYMANAGER_NOT_FOUND_PUBLIC_KEY(ERR_CODE_KEYMANAGER_SIGN_BASE, 		4, "Not found matched public key in did document"),

	ERR_CODE_KEYMANAGER_VC_BASE(1050, ""),
	ERR_CODE_KEYMANAGER_INVALID_VC(ERR_CODE_KEYMANAGER_VC_BASE, 				0, "The vc being provided is invalid"),
	ERR_CODE_KEYMANAGER_EMPTY_VC(ERR_CODE_KEYMANAGER_VC_BASE, 				1, "There has no vc"),
	ERR_CODE_KEYMANAGER_OUT_OF_RANGE_VALUE(ERR_CODE_KEYMANAGER_VC_BASE, 			2, "Out of range value"),
	ERR_CODE_KEYMANAGER_INVALID_PRIVACY(ERR_CODE_KEYMANAGER_VC_BASE, 			3, "Privacy included invalid format or data"),
	ERR_CODE_KEYMANAGER_FILTER_SYNTAX_ERROR(ERR_CODE_KEYMANAGER_VC_BASE, 		4, "Filtering syntax is wrong"),
	ERR_CODE_KEYMANAGER_FILTER_CONDITION_NOT_MATCH(ERR_CODE_KEYMANAGER_VC_BASE,  5, "Filtering condition is not matched"),
	ERR_CODE_KEYMANAGER_DUPLICATED_VC_ID(ERR_CODE_KEYMANAGER_VC_BASE,  		6, "VC Id is duplicated"),
	
	
	ERR_CODE_KEYMANAGER_ECIES_BASE(1070, ""),
	ERR_CODE_KEYMANAGER_ECIES_INVALID_PUBLIC_KEY(ERR_CODE_KEYMANAGER_ECIES_BASE, 	0,		"PublicKey is invalid"),
	ERR_CODE_KEYMANAGER_ECIES_INVALID_PRIVATE_KEY(ERR_CODE_KEYMANAGER_ECIES_BASE, 	1,		"PrivateKey is invalid"),
	ERR_CODE_KEYMANAGER_ECIES_GEN_SECRET_FAIL(ERR_CODE_KEYMANAGER_ECIES_BASE, 		2,		"Failed to generate shared secret"),
	ERR_CODE_KEYMANAGER_NCIPHER_DOES_NOT_SUPPORT_ECIES(ERR_CODE_KEYMANAGER_ECIES_BASE, 		3,		"NCipher HSM does not support ECIES."),

	
	ERR_CODE_KEYMANAGER_DEFAULTKEYSTORE_BASE(1100, ""),
	ERR_CODE_KEYMANAGER_DEFAULTKEYSTORE_KEYGEN_FAIL(ERR_CODE_KEYMANAGER_DEFAULTKEYSTORE_BASE, 0,
			"Key generation in DefaultKeyStore is fail"),
	ERR_CODE_KEYMANAGER_DEFAULTKEYSTORE_AUTHENTICATE_FAIL(ERR_CODE_KEYMANAGER_DEFAULTKEYSTORE_BASE, 1,
			"Authenticating in DefaultKeyStore is fail"),

	
	ERR_CODE_DIDMANAGER_BASE(2000, ""),
	ERR_CODE_DIDMANAGER_FILE_NOT_EXIST(ERR_CODE_DIDMANAGER_BASE, 	 0, "Document file does not exist"),
	
	ERR_CODE_DIDMANAGER_FILE_ALREADY_EXIST(ERR_CODE_DIDMANAGER_BASE, 2, "Document is already existed"),
	ERR_CODE_DIDMANAGER_INVALID_DID_DOCUMENT(ERR_CODE_DIDMANAGER_BASE, 3, "Did document is invalid"),

	ERR_CODE_DIDMANAGER_INVALID_METHODNAME(ERR_CODE_DIDMANAGER_BASE, 4, "Method name must be lower case alphanumeric (colon accepted) and have range between from 1 to 20 length"),
	ERR_CODE_DIDMANAGER_INVALID_PREFIX(ERR_CODE_DIDMANAGER_BASE, 5, "Did Prefix must only be alphaNumeric"),
	
	ERR_CODE_DIDMANAGER_KEY_BASE(2010, ""),
	ERR_CODE_DIDMANAGER_ADD_KEY_FAIL(ERR_CODE_DIDMANAGER_KEY_BASE, 			0,	"Failed to add the key"),
	ERR_CODE_DIDMANAGER_KEYID_ALREADY_EXIST(ERR_CODE_DIDMANAGER_KEY_BASE, 	1, 	"The KeyId already exists in the document"),
	ERR_CODE_DIDMANAGER_KEYID_NOT_EXIST(ERR_CODE_DIDMANAGER_KEY_BASE, 		2, 	"key in did document is not existed"),
	
	ERR_CODE_DIDMANAGER_ASSERTION_BASE(2020, ""),
	ERR_CODE_DIDMANAGER_DID_ASSERITON_TYPE_NOT_CORRECT(ERR_CODE_DIDMANAGER_ASSERTION_BASE, 0,	"Assertion type is not correct"),
	ERR_USER_SIGNATURE_VERIFICATION_FAILED(ERR_CODE_DIDMANAGER_ASSERTION_BASE, 1,	"User signature verification failed"),
	
	ERR_CODE_RECOVERY_MANAGER_BASE(3000, ""),
	ERR_CODE_RECOVERY_MANAGER_INVALID_PASSWORD(ERR_CODE_RECOVERY_MANAGER_BASE, 		 0, "Password is invalid"),
	ERR_CODE_RECOVERY_MANAGER_EMPTY_CONTENT(ERR_CODE_RECOVERY_MANAGER_BASE, 		 1, "There has no data to be backed up"),
	ERR_CODE_RECOVERY_MANAGER_CONTENT_IS_CORRUPTED(ERR_CODE_RECOVERY_MANAGER_BASE, 	 2, "Data is corrupted"),
	ERR_CODE_RECOVERY_MANAGER_CHECKSUM_NOT_MATCH(ERR_CODE_RECOVERY_MANAGER_BASE, 	 3, "Checksum does not match"),
	
	ERR_CODE_RECOVERY_MANAGER_EMPTY_DID_PATH(ERR_CODE_RECOVERY_MANAGER_BASE, 		 5, "Did path(s) is empty"),
	ERR_CODE_RECOVERY_MANAGER_FAILED_TO_GET_DID_PATH(ERR_CODE_RECOVERY_MANAGER_BASE, 6, "Couldn't get the did path"),
	
	
	ERR_CODE_LICENSE_CHECKER_BASE(4000, ""),
	ERR_CODE_LICENSE_CHECKER_INVALID_LICENSE_FILE_NAME(ERR_CODE_LICENSE_CHECKER_BASE, 	0, "Invalid License file name"),
	ERR_CODE_LICENSE_CHECKER_INVALID_PRODUCT_NAME(ERR_CODE_LICENSE_CHECKER_BASE, 		1, "License doesn't match the Product name"),
	ERR_CODE_NO_LICENSE_CHECK(ERR_CODE_LICENSE_CHECKER_BASE, 							2, "No license check"),
	ERR_CODE_LICENSE_CHECKER_INVALID_OPTION_NAME(ERR_CODE_LICENSE_CHECKER_BASE, 3, "License doesn't match the Option Value"),
	
	
	
	ERR_CODE_PRESENTATION_BUILDER_BASE(5000, ""),	
//	ERR_CODE_PRESENTATION_BUILDER_OUT_OF_RANGE_TYPE( ERR_CODE_PRESENTATION_BUILDER_BASE, 			0,  "Out of range type"),
    ERR_CODE_PRESENTATION_BUILDER_INVALID_CREDENTIAL( ERR_CODE_PRESENTATION_BUILDER_BASE, 			1,  "Invalid Credential"),
    ERR_CODE_PRESENTATION_BUILDER_NOT_INCLUDED_CREDENTIAL_ID( ERR_CODE_PRESENTATION_BUILDER_BASE, 	2,  "Credential doesn't include its id"),
    ERR_CODE_PRESENTATION_BUILDER_NOT_INCLUDED_DID( ERR_CODE_PRESENTATION_BUILDER_BASE, 			3,  "Credential doesn't include the user's DID"),
    ERR_CODE_PRESENTATION_BUILDER_NOT_INCLUDED_PRIVACY( ERR_CODE_PRESENTATION_BUILDER_BASE, 		4,  "Credential doesn't include the privacy"),
    ERR_CODE_PRESENTATION_BUILDER_NOT_INCLUDED_SIGNATURE( ERR_CODE_PRESENTATION_BUILDER_BASE,		5,  "Credential doesn't include its signature"),
    ERR_CODE_PRESENTATION_BUILDER_FALSIFIED_CREDENTIAL( ERR_CODE_PRESENTATION_BUILDER_BASE, 		6,  "Credential is falsified"),
    ERR_CODE_PRESENTATION_BUILDER_EMPTY_PRIVACY( ERR_CODE_PRESENTATION_BUILDER_BASE, 				7,  "Given Privacies is empty"),
    ERR_CODE_PRESENTATION_BUILDER_INVALID_PRIVACY( ERR_CODE_PRESENTATION_BUILDER_BASE, 				8,  "Selected Privacies doesn't contain the value which is in credential"),
    ERR_CODE_PRESENTATION_BUILDER_ADD_CREDENTIAL_FAILED( ERR_CODE_PRESENTATION_BUILDER_BASE, 		9,  "No more credentials can be added with the set type"),
    ERR_CODE_PRESENTATION_BUILDER_DID_NOT_MATCHED( ERR_CODE_PRESENTATION_BUILDER_BASE, 				10, "User's DID which included in credential must be same"),
    ERR_CODE_PRESENTATION_BUILDER_DUPLICATED_CREDENTIAL( ERR_CODE_PRESENTATION_BUILDER_BASE, 		11, "Credential is duplicated"),
    ERR_CODE_PRESENTATION_BUILDER_CREDENTIAL_NOT_ADDED( ERR_CODE_PRESENTATION_BUILDER_BASE, 		12, "No credentials have been added"),
    
    ERR_CODE_PRESENTATION_BUILDER_NOT_ALLOWED_ISSUER( ERR_CODE_PRESENTATION_BUILDER_BASE, 			13, "This Credential's Issuer is not allowed"),
    ERR_CODE_PRESENTATION_BUILDER_NOT_ALLOWED_CREDENTIAL_TYPE( ERR_CODE_PRESENTATION_BUILDER_BASE, 	14, "This Credential's type is not allowed"),
    ERR_CODE_PRESENTATION_BUILDER_DUPLICATED_CREDENTIAL_TYPE( ERR_CODE_PRESENTATION_BUILDER_BASE, 	15, "Credential's type must be unique"),
    ERR_CODE_PRESENTATION_BUILDER_SELECTED_PRIVACY_DUPLICATED( ERR_CODE_PRESENTATION_BUILDER_BASE, 	16, "Selected privacies are duplicated"),
    ERR_CODE_PRESENTATION_BUILDER_INSUFFICIENT_PRIVACY( ERR_CODE_PRESENTATION_BUILDER_BASE, 		17, "Required privacies are insufficient"),
	
	ERR_CODE_BCFETCH_BASE(6000, ""),
	ERR_CODE_BCFETCH_INVALID_DID( ERR_CODE_BCFETCH_BASE, 				0,  "The did is invalid for use"),
	ERR_CODE_BCFETCH_INVALID_VC_ID( ERR_CODE_BCFETCH_BASE, 				1,  "The vc id is invalid for use"),
	ERR_CODE_BCFETCH_INVALID_QR_STRING( ERR_CODE_BCFETCH_BASE, 			2,  "The QR code string is invalid for use"),
	ERR_CODE_BCFETCH_NO_REGISTERED_SERVICE_CODE( ERR_CODE_BCFETCH_BASE, 3,  "There is no registered service code"),
	ERR_CODE_BCFETCH_UNREGISTERED_SP_DID( ERR_CODE_BCFETCH_BASE, 		4,  "The SP did is not registered as a service provide"),
	ERR_CODE_BCFETCH_INVALID_CALLBACK( ERR_CODE_BCFETCH_BASE, 			5,  "The callback for using BCFetch is null"),
	ERR_CODE_BCFETCH_NODE_SERVER_ERROR( ERR_CODE_BCFETCH_BASE, 		6,  "Node Server Error"),
	ERR_CODE_BCFETCH_DID_NOT_EXIST    ( ERR_CODE_BCFETCH_BASE, 		7,  "DID is not registered"),
	ERR_CODE_BCFETCH_INVALID_JSON( ERR_CODE_BCFETCH_BASE, 		8,  "The JSON string is invalid for use"),
	
	
	ERR_CODE_DATASPLITTER_BASE(7000, ""),
	ERR_CODE_SPLITTER_INVALID_DATA_SIZE( ERR_CODE_DATASPLITTER_BASE, 				0,   "Data size is insufficient"),
	ERR_CODE_SPLITTER_INVALID_LIST_SIZE( ERR_CODE_DATASPLITTER_BASE, 				1,  "List size must be 2"),
	ERR_CODE_SPLITTER_DUPLICATED_INDEX( ERR_CODE_DATASPLITTER_BASE, 				2, "Indices are duplicated"),
	ERR_CODE_KEYMETHOD_BASE(8000, ""),
	ERR_CODE_INVALID_KEYMETHOD( ERR_CODE_KEYMETHOD_BASE, 				0,   "Method that cannot be used to create dids"),
	;;

	private int code;
	private String msg;

	private IWErrorCode(int code, String msg) {
		this.msg = msg;
		this.code = code;
	}

	private IWErrorCode(IWErrorCode parentCode, int addCode, String msg) {
		this.msg = msg;
		this.code = parentCode.getCode() + addCode;
	}

	@Override
	public String getMsg() {
		return msg;
	}

	@Override
	public int getCode() {
		return code;
	}
	
	public static IWErrorEnumInterface getEnumByCode(int code) {
		
		IWErrorCode agentTypes[] = IWErrorCode.values();
		for (IWErrorCode iwCode : agentTypes) {
			if(iwCode.getCode() == code){
				return iwCode;
			}
		}
		
		throw new AssertionError("Unknown Enum Code");

	}

}
